export const customerManagementcolumns = [
    {
        title: 'Business Name',
        dataIndex: 'name',
        key: 'name',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Contact person',
        dataIndex: 'contactperson',
        key: 'contactperson',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Contact Phone',
        dataIndex: 'contactphone',
        key: 'contactphone',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Contact email',
        dataIndex: 'contactemail',
        key: 'contactemail',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'URL',
        dataIndex: 'url',
        key: 'url',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Action',
        dataIndex: 'action',
        key: 'action',
        width: '',
        isEdit: false,
        nagigate: "",
    }
];


export const customerManagementData = [
    {
      "key": 1,
      "name": "Chandu_13",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 01",
      "contactperson": "Bhanu",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 2,
      "name": "Chandu_2",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 02",
      "contactperson": "Rahul",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 3,
      "name": "Chandu_3",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 03",
      "contactperson": "Rahul",
      "contactphone": 798465123,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 4,
      "name": "Chandu_4",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 04",
      "contactperson": "Rahul",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 5,
      "name": "Chandu_5",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 05",
      "contactperson": "Bhanu",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 6,
      "name": "Chandu_6",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 06",
      "contactperson": "Tulasi",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 7,
      "name": "Chandu_7",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 07",
      "contactperson": "Tulasi",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 8,
      "name": "Chandu_8",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 08",
      "contactperson": "Rahul",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 9,
      "name": "Chandu_9",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 09",
      "contactperson": "Rahul",
      "contactphone": 798465123,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 10,
      "name": "Chandu_10",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 010",
      "contactperson": "Surya",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 11,
      "name": "Chandu_11",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 011",
      "contactperson": "Bhanu",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 12,
      "name": "Chandu_12",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 012",
      "contactperson": "Tulasi",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 13,
      "name": "Chandu_13",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 013",
      "contactperson": "Tulasi",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 14,
      "name": "Chandu_14",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 014",
      "contactperson": "Tulasi",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 15,
      "name": "Chandu_15",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 015",
      "contactperson": "Rahul",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 16,
      "name": "Chandu_16",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 016",
      "contactperson": "Tulasi",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 17,
      "name": "Chandu_17",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 017",
      "contactperson": "Surya",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 18,
      "name": "Chandu_18",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 018",
      "contactperson": "Rahul",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 19,
      "name": "Chandu_19",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 019",
      "contactperson": "Kalyan",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 20,
      "name": "Chandu_20",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 020",
      "contactperson": "Tulasi",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 21,
      "name": "Chandu_21",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 021",
      "contactperson": "Rahul",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 22,
      "name": "Chandu_22",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 022",
      "contactperson": "Tulasi",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 23,
      "name": "Chandu_23",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 023",
      "contactperson": "Tulasi",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 24,
      "name": "Chandu_24",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 024",
      "contactperson": "Rahul",
      "contactphone": 798465123,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 25,
      "name": "Chandu_25",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 025",
      "contactperson": "Bhanu",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 26,
      "name": "Chandu_26",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 026",
      "contactperson": "Tulasi",
      "contactphone": 798465123,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 27,
      "name": "Chandu_27",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 027",
      "contactperson": "Surya",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 28,
      "name": "Chandu_28",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 028",
      "contactperson": "Bhanu",
      "contactphone": 987654321,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 29,
      "name": "Chandu_29",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 029",
      "contactperson": "Surya",
      "contactphone": 234987451,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    },
    {
      "key": 30,
      "name": "Chandu_30",
      "nameImg": "user_icon.png",
      "nameOutlet": "Outlet 030",
      "contactperson": "Subbu",
      "contactphone": 984125875,
      "contactemail": "124544@lorem.com",
      "url": "Lorem",
      "action": ""
    }
  ]