export const salariescolumns = [
    {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Days',
        dataIndex: 'days',
        key: 'days',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'No of OT',
        dataIndex: 'noofot',
        key: 'noofot',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Salary',
        dataIndex: 'salary',
        key: 'salary',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'OT',
        dataIndex: 'ot',
        key: 'ot',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Advnce',
        dataIndex: 'advance',
        key: 'advance',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Deduction',
        dataIndex: 'deduction',
        key: 'deduction',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Remaining',
        dataIndex: 'remaining',
        key: 'remaining',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Total pay',
        dataIndex: 'totalpay',
        key: 'totalpay',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Pay by',
        dataIndex: 'payby',
        key: 'ot',
        width: '',
        isEdit: false,
        nagigate: "",
    },
    {
        title: 'Action',
        dataIndex: 'action',
        key: 'action',
        width: '',
        isEdit: false,
        nagigate: "",
    }
];


export const salariesData = [
    {
        "key": '1',
        "name": 'Chandu',
        "days": '10',
        "nameImg": "user_icon.png",
        "noofot": '8',
        "salary": '5200',
        "ot": '12',
        "advance": '1000',
        "deduction": '1200',
        "remaining": '1080',
        "totalpay": '6000',
        "payby": 'Lorem',
        "action": '',

    },
    {
        "key": '2',
        "name": 'Chandu',
        "days": '10',
        "nameImg": "user_icon.png",
        "noofot": '8',
        "salary": '5200',
        "ot": '12',
        "advance": '1000',
        "deduction": '1200',
        "remaining": '1080',
        "totalpay": '6000',
        "payby": 'Lorem',
        "action": '',
    }
];

export const summaryData = [
    { "displayName": "Total Salary", "value": "12000" },
    { "displayName": "Total OT", "value": "2000" },
    { "displayName": "Total Advance", "value": "5000" },
    { "displayName": "Total Deduction", "value": "1000" },
    { "displayName": "Total Pay", "value": "13000" },
];